name: Cypress Tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: tests/test-site
          start: npm run dev
          project: tests
          config-file: tests/cypress.json