name: Integration tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install monorepo dependencies
        run: npm i

      - name: Build PRPL modules
        run: npm run bootstrap && npm run build

      - name: Install test dependencies
        working-directory: tests
        run: npm i

      - name: Install test site dependencies
        working-directory: tests
        run: npm run setup

      - name: Run tests
        working-directory: tests
        run: npm run test
