name: Integration tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install monorepo dependencies
        run: npm i

      - name: Build PRPL modules
        run: npm run bootstrap && npm run build:all

      - name: Install integration test dependencies
        working-directory: tests/integration
        run: npm i

      - name: Install test site dependencies
        working-directory: tests/test-site
        run: npm i

      - name: Build CJS test site
        working-directory: tests/test-site
        run: npm run build:cjs

      - name: Run CJS integration tests
        working-directory: tests/integration
        run: npm run test

      - name: Build ESM test site
        working-directory: tests/test-site
        run: npm run build:mjs

      - name: Run ESM integration tests
        working-directory: tests/integration
        run: npm run test
